### ISSUE TITLE
Failed to validate resources when create the stack

### ISSUE THREAD

**Issue by zhangjunli177** [redhat-openstack/openshift-on-openstack#206]
root@Oak-controller:~/JJZ/OPENSHIFT/VER3# heat stack-create oakcloud -t 180  -e env_origin.yaml -e openshift-on-openstack/env_loadbalancer_none.yaml -f openshift-on-openstack/openshift.yaml
ERROR: Failed to validate: Failed to validate: resources[0]: At least one of the following properties must be specified: network, network_id

In resource section of openshift.yaml, after I change the fixed_network definition of openshift_masters & openshift_nodes
from fixed_network: {get_attr: [fixed_network, name]}
to fixed_network: {get_resource: fixed_network}
the heat command can be submitted successfully.

In openshift.yaml, infra_host looks like the same level as openshift_masters and openshift_nodes, why fixed_network setting is happy there?

Tried with template validation command: 
w/o change anything:
root@Oak-controller:~/JJZ/OPENSHIFT/TST/openshift-on-openstack# heat template-validate  -n -e env_origin.yaml -f openshift.yaml
ERROR: The Parameter (fixed_network) was not provided.
After I only update the fixed_network setting for openshift_masters in openshift.yaml, the validation can passed. Why fixed_network setting for openshift_nodes is OK with validation but not stack-create?

**Comment by juddmaltin-dell** [comment]
I'm seeing the same thing.  What are we missing?

Here's an strace...   What is resources[0], and why doesn't it have a network or network_id?

connect(4, {sa_family=AF_INET, sin_port=htons(8004), sin_addr=inet_addr("192.168.190.125")}, 16) = 0
sendto(4, "POST /v1/c1b740d8571f4cb5aa66f8d"..., 131477, 0, NULL, 0) = 131477
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(4, F_SETFL, O_RDWR)               = 0
recvfrom(4, "HTTP/1.1 400 Bad Request\r\nConten"..., 8192, 0, NULL, NULL) = 563
write(2, "ERROR: Failed to validate: Faile"..., 140ERROR: Failed to validate: Failed to validate: resources[0]: At least one of the following properties must be specified: network, network
_id) = 140
write(2, "\n", 1
)                       = 1
close(4)                                = 0
close(3)                                = 0
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7ff2a4b8a100}, {0x7ff2a4ea87b0, [], SA_RESTORER, 0x7ff2a4b8a100}, 8) = 0
close(12)                               = 0
exit_group(1)                           = ?
+++ exited with 1 +++
[osp_admin@director ~]$

**Comment by jprovaznik** [comment]
Apparently this one (my) patch broke it - https://github.com/redhat-openstack/openshift-on-openstack/commit/0c8fdae3cc47d8520b1a9ebbee8d63d060e4dc39

As a hotfix you might try reverting the commit, I'll look at this ASAP.

**Comment by juddmaltin-dell** [comment]
#218 

Reversion PR.  WFM.

**Comment by jprovaznik** [comment]
@juddmaltin-dell @zhangjunli177 hm, for some reason I can't reproduce the error "ERROR: Failed to validate: Failed to validate: resources[0]: At least one of the following properties must be specified: network, network_id" on stack-create. Could you please provide parameters (eventaully content of env file) you use?

**Comment by juddmaltin-dell** [comment]
```
parameters:
  internal_subnet: 192.168.10.0/24
  container_subnet: 10.10.0.0/24
  ssh_key_name: key_name
  infra_image: rhel72
  master_image: rhel72
  node_image: rhel72
  flavor: m1.medium
  external_network: nova
  dns_nameserver: 8.8.4.4,8.8.8.8
  node_count: 3
  rhn_username: "SECRET"
  rhn_password: "SECRET"
  rhn_pool: 'OBSCURE'
  deployment_type: openshift-enterprise
  domain_name: "10example.com"
  master_hostname: "openshift-master"
  node_hostname: "openshift-node"
  ssh_user: cloud-user
  master_docker_volume_size_gb: 25
  node_docker_volume_size_gb: 25
  extra_rhn_pools: 'OBSCURE'
  master_count: 2
  master_server_group_policies: affinity
  deploy_registry: false
  os_auth_url: http://192.168.190.125:5000/v2.0
  os_username: admin
  os_password: OBSCURE
  os_tenant_name: admin
  openshift_ansible_git_url: https://github.com/openshift/openshift-ansible.git
  #openshift_ansible_git_rev: 08791978fdf3ee385760761d4fc6bc47febf1732
  openshift_ansible_git_rev: master

resource_registry:
  OOShift::LoadBalancer: openshift-on-openstack/loadbalancer_neutron.yaml
  OOShift::ContainerPort: openshift-on-openstack/sdn_flannel.yaml
  OOShift::IPFailover: openshift-on-openstack/ipfailover_keepalived.yaml
  OOShift::DockerVolume: openshift-on-openstack/volume_docker.yaml
  OOShift::DockerVolumeAttachment: openshift-on-openstack/volume_attachment_docker.yaml
  OOShift::RegistryVolume: openshift-on-openstack/registry_ephemeral.yaml
``
```
