### ISSUE TITLE
No DNS Server deployed

### ISSUE THREAD

**Issue by DENEUBOURG** [redhat-openstack/openshift-on-openstack#325]
Hello all,
I tried to deploy an Openshift environment on Openstack using Openshift-on-Openstack's Heat scripts. Deployment fails. I'm probably wrong with my configuration or misunderstood something, but it seem's no DNS is provisioned with stack.
_Referring to documentation: 

> A bastion server is used to control the host and service configuration. It can also run local DNS services as needed.

_

0. Below is my openshift_parameters.yaml" file content
```
parameters:
  ssh_key_name: adminKey
  bastion_image: centos72
  bastion_flavor: m1.medium
  master_image: centos72
  master_flavor: m1.medium
  infra_image: centos72
  infra_flavor: m1.medium
  node_image: centos72
  node_flavor: m1.medium
  external_network: external_network
  dns_nameserver: 8.8.4.4,8.8.8.8
  node_count: 2
  deployment_type: origin
  domain_name: "192.168.1.50.xip.io"
  master_hostname: "origin-master"
  node_hostname: "origin-node"
  ssh_user: centos
  master_docker_volume_size_gb: 25
  infra_docker_volume_size_gb: 25
  node_docker_volume_size_gb: 25
  openshift_ansible_git_url: https://github.com/openshift/openshift-ansible.git
  openshift_ansible_git_rev: master
  loadbalancer_type: 'external'

resource_registry:
  OOShift::LoadBalancer: loadbalancer_external.yaml
  OOShift::ContainerPort: sdn_openshift_sdn.yaml
  OOShift::IPFailover: ipfailover_none.yaml
  OOShift::DockerVolume: volume_docker.yaml
  OOShift::DockerVolumeAttachment: volume_attachment_docker.yaml
  OOShift::RegistryVolume: registry_ephemeral.yaml
```

1. Getting Heat logs from Openstack:
```
[root@rdo-openstack openshift-on-openstack(keystone_admin)]# heat event-list -n 2 my-openshift | grep FAIL
WARNING (shell) "heat event-list" is deprecated, please use "openstack stack event list" instead
| deployment_run_ansible                                              | 23309ba1-9e48-4320-b138-0fe1c48df6c6 | Error: resources.deployment_run_ansible: Deployment to server failed: deploy_status_code : Deployment exited with non-zero status code: 1                                                                                                                       | CREATE_FAILED      | 2017-03-13T23:31:06Z | my-openshift |
| my-openshift-openshift_nodes-y6dfoa7q3i25-7xmmeigbufq4-t2ht77rrdef4 | 9c666062-c517-4fde-a0c8-e697a32a8277 | Resource CREATE failed: Error: resources.deployment_run_ansible: Deployment to server failed: deploy_status_code : Deployment exited with non-zero status code: 1                                                                                               | CREATE_FAILED      | 2017-03-13T23:31:06Z | my-openshift |
| 7xmmeigbufq4                                                        | db0b09ce-18ec-4fbb-b7d2-73c54554745e | Error: resources.7xmmeigbufq4.resources.deployment_run_ansible: Deployment to server failed: deploy_status_code: Deployment exited with non-zero status code: 1                                                                                                 | CREATE_FAILED      | 2017-03-13T23:31:07Z | my-openshift |
| my-openshift-openshift_nodes-y6dfoa7q3i25                           | 37557714-cf45-4fff-8e98-e0e2ce577666 | Resource CREATE failed: Error: resources.7xmmeigbufq4.resources.deployment_run_ansible: Deployment to server failed: deploy_status_code: Deployment exited with non-zero status code: 1                                                                         | CREATE_FAILED      | 2017-03-13T23:31:07Z | my-openshift |
| openshift_nodes                                                     | db0ae17f-e459-488e-8006-58f28913d0c0 | Error: resources.openshift_nodes.resources.7xmmeigbufq4.resources.deployment_run_ansible: Deployment to server failed: deploy_status_code: Deployment exited with non-zero status code: 1                                                                       | CREATE_FAILED      | 2017-03-13T23:31:07Z | my-openshift |
| my-openshift                                                        | 75451b85-316c-4f37-a4d6-ec31da7ce91b | Resource CREATE failed: Error: resources.openshift_nodes.resources.7xmmeigbufq4.resources.deployment_run_ansible: Deployment to server failed: deploy_status_code: Deployment exited with non-zero status code: 1                                               | CREATE_FAILED      | 2017-03-13T23:31:07Z | my-openshift |
| deployment_run_ansible                                              | a97a4a86-1656-4e16-aa1a-6bbf1a3a0d71 | Error: resources.deployment_run_ansible: Deployment to server failed: deploy_status_code : Deployment exited with non-zero status code: 1                                                                                                                       | CREATE_FAILED      | 2017-03-13T23:31:30Z | my-openshift |
| my-openshift-openshift_nodes-y6dfoa7q3i25-kgyu2v2lka2g-4z2mzly26iku | bd01ca20-a895-4040-a289-9c7a2dcdfd61 | Resource CREATE failed: Error: resources.deployment_run_ansible: Deployment to server failed: deploy_status_code : Deployment exited with non-zero status code: 1                                                                                               | CREATE_FAILED      | 2017-03-13T23:31:30Z | my-openshift |
| kgyu2v2lka2g                                                        | 91bedb29-07f6-46a7-b163-b50f7b8c72ed | Error: resources.kgyu2v2lka2g.resources.deployment_run_ansible: Deployment to server failed: deploy_status_code: Deployment exited with non-zero status code: 1                                                                                                 | CREATE_FAILED      | 2017-03-13T23:31:30Z | my-openshift |
| my-openshift-openshift_nodes-y6dfoa7q3i25                           | 186f76e4-2cb7-439c-8ece-caba407f2934 | Resource CREATE failed: Error: resources.kgyu2v2lka2g.resources.deployment_run_ansible: Deployment to server failed: deploy_status_code: Deployment exited with non-zero status code: 1                                                                         | CREATE_FAILED      | 2017-03-13T23:31:31Z | my-openshift |

[root@rdo-openstack openshift-on-openstack(keystone_admin)]# openstack stack event list my-openshift | grep FAIL
2017-03-13 23:31:07Z [my-openshift.openshift_nodes]: CREATE_FAILED  Error: resources.openshift_nodes.resources.7xmmeigbufq4.resources.deployment_run_ansible: Deployment to server failed: deploy_status_code: Deployment exited with non-zero status code: 1
2017-03-13 23:31:07Z [my-openshift]: CREATE_FAILED  Resource CREATE failed: Error: resources.openshift_nodes.resources.7xmmeigbufq4.resources.deployment_run_ansible: Deployment to server failed: deploy_status_code: Deployment exited with non-zero status code: 1
```

2. I manually ran playbook (as sudo) from Bastion Instance:
```
ansible-playbook -vvvv --inventory /var/lib/ansible/inventory /var/lib/ansible/playbooks/main.yml
```

I got errors below:
```
[...]
TASK [setup] *******************************************************************
[...]
fatal: [my-openshift-origin-master-0.192.168.1.50.xip.io]: UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
fatal: [my-openshift-origin-node-2wm64749.192.168.1.50.xip.io]: UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
fatal: [my-openshift-origin-node-8e100024.192.168.1.50.xip.io]: UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
fatal: [my-openshift-infra-0.192.168.1.50.xip.io]: UNREACHABLE! => {
    "changed": false,
    "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh",
    "unreachable": true
}
[...]
PLAY RECAP *********************************************************************
localhost                  : ok=14   changed=2    unreachable=0    failed=0
my-openshift-infra-0.192.168.1.50.xip.io : ok=0    changed=0    unreachable=1    failed=0
my-openshift-origin-master-0.192.168.1.50.xip.io : ok=0    changed=0    unreachable=1    failed=0
my-openshift-origin-node-2wm64749.192.168.1.50.xip.io : ok=0    changed=0    unreachable=1    failed=0
my-openshift-origin-node-8e100024.192.168.1.50.xip.io : ok=0    changed=0    unreachable=1    failed=0
```

4. Then I had a look on netstat
```
[root@my-openshift-bastion log]# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      7883/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1217/master
tcp6       0      0 :::111                  :::*                    LISTEN      1/systemd
tcp6       0      0 :::22                   :::*                    LISTEN      7883/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      1217/master
```

So clearly, I haven't got any DNS server deployed on my Bastion instance...
**How should I proceed to get this service automatically deployed with my stack?**

Thanks in advance for your help.
