### ISSUE TITLE
support for Aodh and Gnocchi alarms

### ISSUE THREAD

**Issue by ioggstream** [redhat-openstack/openshift-on-openstack#353]
### reproduce

  1. deploy on rhosp10 with autoscaling: true
  2. issue `openstack alarm list`

### I expect

Alarm status to be in [ "ok", "alarm" ]

### instead

Alarm status is "insufficient data"

### my resolution

  - replace metadata on ServerGroup with the following.
 
```
          metadata: {"metering.server_group": {get_param: "OS::stack_id"}}
```

  - create Gnocchi + Aodh alarms like this

```
  cpu_alarm_high:
    type: OS::Aodh::GnocchiAggregationByResourcesAlarm
    properties:
      aggregation_method: mean
      metric: cpu_util
      comparison_operator: gt
      threshold: 50
      granularity: 600
      evaluation_periods: 1
      resource_type: instance
      enabled: {get_param: autoscaling}
      alarm_actions:
        - {get_attr: [scale_up_policy, alarm_url]}
      query:
        str_replace:
          template: '{"=": {"server_group": "stack_id"}}'
          params:
            stack_id: {get_param: "OS::stack_id"}
```
  

Feedback welcome!

Peace,
R:
