### ISSUE TITLE
resources.external_router: No more IP addresses    

### ISSUE THREAD

**Issue by rawlingsj** [redhat-openstack/openshift-on-openstack#39]
I'm trying to use the openshift-on-openstack scripts however I'm running into the issue below after running `heat stack-create`.  I'm an openstack novice so I'm sure its down to my setup or config but I'm not sure what.  I've checked and I have 5 free floating ips when I check in the openstack console under the external-network that I specify.
Any ideas or pointers where to start looking?

```
heat stack-create my_openshift -t 180 -e env.yaml -e openshift-on-openstack/env_single.yaml -f openshift-on-openstack/openshift.yaml
```

then checking the status with..

```
heat stack-show my_openshift
```

```
| parent                | None                                                                                                                                                                                                   |
| stack_name            | my_openshift                                                                                                                                                                                           |
| stack_owner           | admin                                                                                                                                                                                                  |
| stack_status          | CREATE_FAILED                                                                                                                                                                                          |
| stack_status_reason   | Resource CREATE failed:                                                                                                                                                                                |
|                       | IpAddressGenerationFailureClient:                                                                                                                                                                      |
|                       | resources.external_router: No more IP addresses                                                                                                                                                        |
|                       | available on network                                                                                                                                                                                   |
|                       | 2ac90f7c-d409-4a80-8392-c333b1bf050e.                                                                                                                                                                  |
| stack_user_project_id | ae945c26a4464612a76a17c7af18dc7e                                                                                                                                                                       |
| template_description  | Deploy Atomic/OpenShift 3 on OpenStack.                                                                                                                                                                |
| timeout_mins          | 180                                                                                                                                                                                                    |
| updated_time          | None                                                                                                                                                                                                   |                                                                                                                                                                              
```

This is the config I'm using...

```
cat << EOF > env.yaml
parameters:
  ssh_key_name: jr-mac
  server_image: centos72
  flavor: m1.medium
  external_network: external_network
  dns_nameserver: 8.8.4.4,8.8.8.8
  node_count: 2
  rhn_username: "myusername"
  rhn_password: "****"
  rhn_pool: '****'
  deployment_type: origin
  domain_name: "origin.fabric8.io"
  dns_hostname: "ns"
  master_hostname_prefix: "origin-master"
  node_hostname_prefix: "origin-node"
  ssh_user: centos
  master_docker_volume_size_gb: 45
  node_docker_volume_size_gb: 45
  deploy_router: False
  deploy_registry: False
  openshift_ansible_git_url: https://github.com/openshift/openshift-ansible.git
  openshift_ansible_git_rev: master
EOF
```
