### ISSUE TITLE
set ca-certificate 

### ISSUE THREAD

**Issue by mahsa-frj** [redhat-openstack/openshift-on-openstack#390]
I set certificate on two sections in master-config.yaml and put the .cer and .key file in the same path with config file. 

> /etc/origin/master/key.cer
> /etc/origin/master/keey.key
> /etc/origin/master/master-config.yaml

1:
```
apiVersion: v1
  ....
  servingInfo:
    namedCertificates:
    - certFile: /etc/origin/master/key.cer
      keyFile: /etc/origin/master/keey.key
      names:
      - "example.com"
    openshift_master_overwrite_named_certificates: true
```
2:
```
servingInfo:
  ...
  namedCertificates:
  - certFile: /etc/origin/master/key.cer
    keyFile: /etc/origin/master/keey.key
    names:
    - "example.com"
  openshift_master_overwrite_named_certificates: true
```
But the  example.com:8443 is not secure yet. what is the problem?
