### ISSUE TITLE
We should download and Centos immage by default. 

### ISSUE THREAD

**Issue by sferich888** [redhat-openstack/openshift-on-openstack#74]
It would be nice to have the template reach out and collect the image, that is needed to run the template. 

The following can do this: 

```
heat_template_version: 2014-10-16

description: A hot template for provisioning an Glance Image

parameters:

  image_name: 
    type: string
    default: "Centos7" 

  container_format:
    type: string
    default: "bare"
    constraints:
      - allowed_values: [ "ami", "ari", "aki", "bare", "ova", "ovf"]

  disk_format:
    type: string
    default: "qcow2"
    constraints:
      - allowed_values: [ "ami", "ari", "aki", "vhd", "vmdk", "raw", "qcow2", "vdi", "iso" ]

  location: 
    type: string
    default: "http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2" 

  public: 
    type: boolean
    default: true

  protected:
    type: boolean
    default: false

  disk_min:
    type: integer
    default: 0

  ram_min: 
    type: integer
    default: 0

resources:

  image:
    type: OS::Glance::Image
    properties:
      container_format: {get_param: container_format} 
      disk_format: {get_param: disk_format}
      is_public: {get_param: public}
      location: {get_param: location}
      min_disk: {get_param: disk_min}
      min_ram: {get_param: ram_min}
      name: {get_param: image_name}
      protected: {get_param: protected}

outputs: 
 image_name:
    description: Image Name
    value: { get_param: image_name}
```

However the trick is in finding a way to make this optional.
