### ISSUE TITLE
heat stack-create fails; Deployment exited with non-zero status code: 4

### ISSUE THREAD

**Issue by rawlingsj** [redhat-openstack/openshift-on-openstack#91]
Using command.. `heat stack-create my_openshift -t 260 -e openshift_parameters.yaml -f openshift-on-openstack/openshift.yaml -e openshift-on-openstack/env_loadbalancer_none.yaml`

```
parameters:
   # Use OpenShift Origin (vs Openshift Enterprise)
   deployment_type: origin

   # set SSH access to VMs
   ssh_user: centos
   ssh_key_name: jr-mac

   # Set the image type and size for the VMs
   server_image: centos72
   flavor: m1.large

   # Set an existing network for inbound and outbound traffic
   external_network: external_network
   dns_nameserver: 10.34.32.1

   # Define the host name templates for master and nodes
   domain_name: "origin.fabric8.io"
   master_hostname: "origin-master"
   node_hostname: "origin-node"

   # Allocate additional space for Docker images
   master_docker_volume_size_gb: 40
   node_docker_volume_size_gb: 40

   # Specify the (initial) number of nodes to deploy
   node_count: 2

   # Add auxiliary services: OpenStack router and internal Docker registry
   deploy_router: True
   deploy_registry: True

   # If using RHEL image, add RHN credentials for RPM installation on VMs
   rhn_username: ""
   rhn_password: ""
   rhn_pool: '' # OPTIONAL

   openshift_ansible_git_url: https://github.com/openshift/openshift-ansible.git
   openshift_ansible_git_rev: master
```

Results in..

```
| stack_status_reason   | Resource CREATE failed: Error: resources.openshift_node                                                                                                                                                |
|                       | s.resources.zrtf3m3figae.resources.deployment_run_ansib                                                                                                                                                |
|                       | le: Deployment to server failed: deploy_status_code:                                                                                                                                                   |
|                       | Deployment exited with non-zero status code: 4                                                                                                                                                         |
```

I'm not too sure where to look for logs or what went wrong.  Any ideas or pointers?  I can see the openstack resources were created so I think it's openshift ansible scripts that's failing?
